export const SET_LOCATION = 'SET_LOCATION';
export const SET_LOCATION_SUCCESS = 'SET_LOCATION_SUCCESS';
export const SET_LOCATION_FAILED = 'SET_LOCATION_FAILED';

export const GET_GEO_NAME_ID = 'GET_GEO_NAME_ID';
export const GET_GEO_NAME_ID_SUCCESS = 'GET_GEO_NAME_ID_SUCCESS';
export const GET_GEO_NAME_ID_FAILED = 'GET_GEO_NAME_ID_FAILED';

export const GET_FIVE_DAY_FORECAST_DATA = 'GET_FIVE_DAY_FORECAST_DATA';
export const GET_FIVE_DAY_FORECAST_DATA_SUCCESS = 'GET_FIVE_DAY_FORECAST_DATA_SUCCESS';
export const GET_FIVE_DAY_FORECAST_DATA_FAILED = 'GET_FIVE_DAY_FORECAST_DATA_FAILED';

export const SET_DAY_SHOWING = 'SET_DAY_SHOWING';